apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bezz-backend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
        deployment.timestamp: "1753649400"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: bezz-backend-sa@bezz-777eb.iam.gserviceaccount.com
      containers:
      - image: gcr.io/bezz-777eb/bezz-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        - name: GOOGLE_CLOUD_PROJECT
          value: "981046325818"
        resources:
          limits:
            cpu: "1000m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi" 