version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8081
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8080"
    volumes:
      - ./backend:/app
    environment:
      - PORT=8080
      - GIN_MODE=debug
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account.json
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
    env_file:
      - .env

volumes:
  node_modules: 